### ISSUE TITLE
Ingreso a la aplicación sin haber iniciado sesión

### ISSUE THREAD

**Issue by Confectus** [Confectus/mascotinder#1]
Los usuarios pueden ingresar a cualquiera de las interfaces internas de la aplicación sin antes de haber iniciado sesión. Esto es posible ingresando la URL de la interfaz o del controlador directamente en el navegador web.

**Comment by jonap22** [comment]
Issue has been fixed by adding additional statements into "controllers" path.

**Comment by jonap22** [comment]
Implementation is done for "controllers" path.
